server:
  port: 8090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    hibernate:
      ddl-auto: create-drop

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
